name: build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/kaesaecracker/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Print directory contents
      run: ls -lah
    - name: Definitions
      run: dotnet pack --configuration Release --output nupkgs TrivialUno.Definitions
    - name: DefaultCards
      run: dotnet pack --configuration Release --output nupkgs TrivialUno.DefaultCards
    - name: Push main
      if: ${{ env.GITHUB_REF_NAME == main }}
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}
    - name: Push other
      if: ${{ env.GITHUB_REF_NAME != main }
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --version-sufix r${{ env.GITHUB_RUN_NUMBER }}-${{ env.GITHUB_REF_NAME }}

